# Generated by Django 2.2.4 on 2020-03-17 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity_donation', '0004_auto_20200310_1747'),
        ('charity_donation', '0004_donation_is_taken'),
    ]

    operations = [
    ]
